// Auto-extracted from index.html COMPONENTS_JSON (game component catalog).
// Used by the grade-backfill migration. field = grade (Mil/Civ/...), grade = tier (A/B/C/D).
export const COMPONENTS_JSON: {name:string;category:string;field:string;size:number;grade:string}[] = [
  {name:'IcePlunge',category:'cooler',field:'Cmp',size:1,grade:'C'},
  {name:'QuikCool',category:'cooler',field:'Cmp',size:1,grade:'D'},
  {name:'AbsoluteZero',category:'cooler',field:'Cmp',size:2,grade:'B'},
  {name:'IceDive',category:'cooler',field:'Cmp',size:2,grade:'C'},
  {name:'RapidCool',category:'cooler',field:'Cmp',size:2,grade:'D'},
  {name:'ZeroRush',category:'cooler',field:'Cmp',size:1,grade:'B'},
  {name:'Bracer',category:'cooler',field:'Mil',size:1,grade:'C'},
  {name:'Glacier',category:'cooler',field:'Mil',size:1,grade:'A'},
  {name:'Polar',category:'cooler',field:'Mil',size:1,grade:'B'},
  {name:'Tundra',category:'cooler',field:'Mil',size:1,grade:'D'},
  {name:'Arctic',category:'cooler',field:'Mil',size:2,grade:'C'},
  {name:'Boreal',category:'cooler',field:'Mil',size:2,grade:'D'},
  {name:'Avalanche',category:'cooler',field:'Mil',size:2,grade:'A'},
  {name:'Permafrost',category:'cooler',field:'Mil',size:2,grade:'B'},
  {name:'Blizzard',category:'cooler',field:'Mil',size:3,grade:'A'},
  {name:'Galinstan',category:'cooler',field:'Mil',size:3,grade:'D'},
  {name:'Mercury',category:'cooler',field:'Mil',size:3,grade:'C'},
  {name:'Tempest',category:'cooler',field:'Mil',size:3,grade:'B'},
  {name:'Frost-Star SL',category:'cooler',field:'Civ',size:0,grade:'C'},
  {name:'Winter-Star SL',category:'cooler',field:'Civ',size:0,grade:'D'},
  {name:'Cryo-Star SL',category:'cooler',field:'Civ',size:0,grade:'B'},
  {name:'Fridan',category:'cooler',field:'Civ',size:0,grade:'C'},
  {name:'Tepilo',category:'cooler',field:'Civ',size:0,grade:'A'},
  {name:'Kelvid',category:'cooler',field:'Civ',size:0,grade:'B'},
  {name:'Cryo-Star',category:'cooler',field:'Civ',size:1,grade:'B'},
  {name:'Frost-Star',category:'cooler',field:'Civ',size:1,grade:'C'},
  {name:'Winter-Star',category:'cooler',field:'Civ',size:1,grade:'D'},
  {name:'ArcticStorm',category:'cooler',field:'Civ',size:1,grade:'C'},
  {name:'BlastChill',category:'cooler',field:'Civ',size:1,grade:'D'},
  {name:'FlashFreeze',category:'cooler',field:'Civ',size:1,grade:'B'},
  {name:'Berian',category:'cooler',field:'Civ',size:1,grade:'C'},
  {name:'Endo',category:'cooler',field:'Civ',size:1,grade:'B'},
  {name:'Gelid',category:'cooler',field:'Civ',size:1,grade:'A'},
  {name:'Cryo-Star EX',category:'cooler',field:'Civ',size:2,grade:'B'},
  {name:'Frost-Star EX',category:'cooler',field:'Civ',size:2,grade:'C'},
  {name:'Winter-Star EX',category:'cooler',field:'Civ',size:2,grade:'D'},
  {name:'ColdSnap',category:'cooler',field:'Civ',size:2,grade:'C'},
  {name:'Aufeis',category:'cooler',field:'Civ',size:2,grade:'A'},
  {name:'Graupel',category:'cooler',field:'Civ',size:2,grade:'C'},
  {name:'Taiga',category:'cooler',field:'Civ',size:2,grade:'B'},
  {name:'FullFrost',category:'cooler',field:'Civ',size:2,grade:'B'},
  {name:'WhiteOut',category:'cooler',field:'Civ',size:2,grade:'D'},
  {name:'Frost-Star XL',category:'cooler',field:'Civ',size:3,grade:'C'},
  {name:'Winter-Star XL',category:'cooler',field:'Civ',size:3,grade:'D'},
  {name:'ColdSurge',category:'cooler',field:'Civ',size:3,grade:'D'},
  {name:'FrostBurn',category:'cooler',field:'Civ',size:3,grade:'C'},
  {name:'Draug',category:'cooler',field:'Civ',size:3,grade:'C'},
  {name:'Elsen',category:'cooler',field:'Civ',size:3,grade:'B'},
  {name:'Kragen',category:'cooler',field:'Civ',size:3,grade:'A'},
  {name:'Cryo-Star XL',category:'cooler',field:'Civ',size:3,grade:'B'},
  {name:'FrostBite',category:'cooler',field:'Civ',size:3,grade:'B'},
  {name:'EcoFlow',category:'cooler',field:'Ind',size:1,grade:'B'},
  {name:'Hydrocel',category:'cooler',field:'Ind',size:1,grade:'D'},
  {name:'Thermax',category:'cooler',field:'Ind',size:1,grade:'C'},
  {name:'Eco-Flow',category:'cooler',field:'Ind',size:1,grade:'B'},
  {name:'Ultra-Flow',category:'cooler',field:'Ind',size:1,grade:'A'},
  {name:'CoolCore',category:'cooler',field:'Ind',size:2,grade:'C'},
  {name:'HydroJet',category:'cooler',field:'Ind',size:2,grade:'D'},
  {name:'Snowpack',category:'cooler',field:'Ind',size:2,grade:'A'},
  {name:'Snowfall',category:'cooler',field:'Ind',size:2,grade:'B'},
  {name:'Chill-Max',category:'cooler',field:'Ind',size:3,grade:'A'},
  {name:'Hydropulse',category:'cooler',field:'Ind',size:3,grade:'D'},
  {name:'ThermalCore',category:'cooler',field:'Ind',size:3,grade:'C'},
  {name:'Ice-Flush',category:'cooler',field:'Ind',size:3,grade:'B'},
  {name:'HeatSafe',category:'cooler',field:'Sth',size:1,grade:'C'},
  {name:'VaporBlock',category:'cooler',field:'Sth',size:1,grade:'B'},
  {name:'SnowBlind',category:'cooler',field:'Sth',size:1,grade:'A'},
  {name:'HeatSink',category:'cooler',field:'Sth',size:2,grade:'C'},
  {name:'IceBox',category:'cooler',field:'Sth',size:2,grade:'B'},
  {name:'NightFall',category:'cooler',field:'Sth',size:2,grade:'A'},
  {name:'StarHeart',category:'power',field:'Cmp',size:1,grade:'B'},
  {name:'Sunflare',category:'power',field:'Cmp',size:1,grade:'C'},
  {name:'LumaCore',category:'power',field:'Cmp',size:1,grade:'A'},
  {name:'LuxCore',category:'power',field:'Cmp',size:2,grade:'A'},
  {name:'StarBurn',category:'power',field:'Cmp',size:2,grade:'B'},
  {name:'SolarFlare',category:'power',field:'Cmp',size:2,grade:'C'},
  {name:'Charger',category:'power',field:'Mil',size:1,grade:'D'},
  {name:'Fierell Cascade',category:'power',field:'Mil',size:1,grade:'B'},
  {name:'Regulus',category:'power',field:'Mil',size:1,grade:'C'},
  {name:'HyperGen',category:'power',field:'Mil',size:1,grade:'D'},
  {name:'JS-300',category:'power',field:'Mil',size:1,grade:'A'},
  {name:'OverDrive',category:'power',field:'Mil',size:1,grade:'C'},
  {name:'QuadraCell',category:'power',field:'Mil',size:1,grade:'A'},
  {name:'DynaFlux',category:'power',field:'Mil',size:1,grade:'B'},
  {name:'Maelstrom',category:'power',field:'Mil',size:2,grade:'C'},
  {name:'QuadraCell MT',category:'power',field:'Mil',size:2,grade:'A'},
  {name:'Vortex',category:'power',field:'Mil',size:2,grade:'D'},
  {name:'ExoGen',category:'power',field:'Mil',size:2,grade:'D'},
  {name:'JS-400',category:'power',field:'Mil',size:2,grade:'A'},
  {name:'UltraFlux',category:'power',field:'Mil',size:2,grade:'B'},
  {name:'Bolide',category:'power',field:'Mil',size:2,grade:'B'},
  {name:'TurboDrive',category:'power',field:'Mil',size:2,grade:'C'},
  {name:'Drassik',category:'power',field:'Mil',size:3,grade:'D'},
  {name:'QuadraCell MX',category:'power',field:'Mil',size:3,grade:'A'},
  {name:'JS-500',category:'power',field:'Mil',size:3,grade:'A'},
  {name:'SuperDrive',category:'power',field:'Mil',size:3,grade:'C'},
  {name:'MegaFlux',category:'power',field:'Mil',size:3,grade:'B'},
  {name:'SmartGen',category:'power',field:'Mil',size:3,grade:'D'},
  {name:'Centurion',category:'power',field:'Mil',size:3,grade:'C'},
  {name:'Fulgur',category:'power',field:'Mil',size:3,grade:'B'},
  {name:'Jennet',category:'power',field:'Ind',size:0,grade:'D'},
  {name:'Steadfast',category:'power',field:'Ind',size:0,grade:'C'},
  {name:'Defiant',category:'power',field:'Ind',size:0,grade:'B'},
  {name:'Endurance',category:'power',field:'Ind',size:1,grade:'B'},
  {name:'Roughneck',category:'power',field:'Ind',size:1,grade:'D'},
  {name:'Breton',category:'power',field:'Ind',size:1,grade:'A'},
  {name:'Genoa',category:'power',field:'Ind',size:2,grade:'A'},
  {name:'Trommel',category:'power',field:'Ind',size:2,grade:'D'},
  {name:'Diligence',category:'power',field:'Ind',size:2,grade:'C'},
  {name:'Sedulity',category:'power',field:'Ind',size:2,grade:'B'},
  {name:'Ginzel',category:'power',field:'Ind',size:3,grade:'C'},
  {name:'Durango',category:'power',field:'Ind',size:3,grade:'A'},
  {name:'Reliance',category:'power',field:'Ind',size:3,grade:'B'},
  {name:'DuraJet',category:'power',field:'Civ',size:0,grade:'D'},
  {name:'Radix',category:'power',field:'Civ',size:0,grade:'C'},
  {name:'IonWave',category:'power',field:'Civ',size:0,grade:'B'},
  {name:'IonBurst',category:'power',field:'Civ',size:1,grade:'B'},
  {name:'PowerBolt',category:'power',field:'Civ',size:1,grade:'C'},
  {name:'ZapJet',category:'power',field:'Civ',size:1,grade:'D'},
  {name:'LightBlossom',category:'power',field:'Civ',size:1,grade:'C'},
  {name:'WhiteRose',category:'power',field:'Civ',size:1,grade:'A'},
  {name:'MagnaBloom',category:'power',field:'Civ',size:1,grade:'B'},
  {name:'FullForce',category:'power',field:'Civ',size:2,grade:'C'},
  {name:'IonSurge',category:'power',field:'Civ',size:2,grade:'B'},
  {name:'DayBreak',category:'power',field:'Civ',size:2,grade:'C'},
  {name:'Lotus',category:'power',field:'Civ',size:2,grade:'A'},
  {name:'Radiance',category:'power',field:'Civ',size:2,grade:'B'},
  {name:'SparkJet',category:'power',field:'Civ',size:2,grade:'D'},
  {name:'FullForce Pro',category:'power',field:'Civ',size:3,grade:'C'},
  {name:'SparkJet Pro',category:'power',field:'Civ',size:3,grade:'D'},
  {name:'TigerLilly',category:'power',field:'Civ',size:3,grade:'A'},
  {name:'Celestial',category:'power',field:'Civ',size:3,grade:'B'},
  {name:'NewDawn',category:'power',field:'Civ',size:3,grade:'C'},
  {name:'IonSurge Pro',category:'power',field:'Civ',size:3,grade:'B'},
  {name:'DeltaMax',category:'power',field:'Sth',size:1,grade:'B'},
  {name:'SonicLite',category:'power',field:'Sth',size:1,grade:'C'},
  {name:'Slipstream',category:'power',field:'Sth',size:1,grade:'A'},
  {name:'Eclipse',category:'power',field:'Sth',size:2,grade:'A'},
  {name:'GammaMax',category:'power',field:'Sth',size:2,grade:'B'},
  {name:'Cirrus',category:'power',field:'Sth',size:2,grade:'C'},
  {name:'FoxFire',category:'quantum',field:'Cmp',size:1,grade:'B'},
  {name:'LightFire',category:'quantum',field:'Cmp',size:1,grade:'C'},
  {name:'SparkFire',category:'quantum',field:'Cmp',size:2,grade:'C'},
  {name:'SunFire',category:'quantum',field:'Cmp',size:2,grade:'B'},
  {name:'Burst',category:'quantum',field:'Civ',size:1,grade:'B'},
  {name:'Flood',category:'quantum',field:'Civ',size:1,grade:'D'},
  {name:'Rush',category:'quantum',field:'Civ',size:1,grade:'C'},
  {name:'Atlas',category:'quantum',field:'Civ',size:1,grade:'A'},
  {name:'Eos',category:'quantum',field:'Civ',size:1,grade:'C'},
  {name:'Hyperion',category:'quantum',field:'Civ',size:1,grade:'B'},
  {name:'Expedition',category:'quantum',field:'Civ',size:1,grade:'C'},
  {name:'Voyage',category:'quantum',field:'Civ',size:1,grade:'B'},
  {name:'Wayfare',category:'quantum',field:'Civ',size:1,grade:'D'},
  {name:'Aither',category:'quantum',field:'Civ',size:2,grade:'B'},
  {name:'Hemera',category:'quantum',field:'Civ',size:2,grade:'A'},
  {name:'Cascade',category:'quantum',field:'Civ',size:2,grade:'D'},
  {name:'Flash',category:'quantum',field:'Civ',size:2,grade:'B'},
  {name:'Torrent',category:'quantum',field:'Civ',size:2,grade:'C'},
  {name:'Khaos',category:'quantum',field:'Civ',size:2,grade:'C'},
  {name:'Odyssey',category:'quantum',field:'Civ',size:2,grade:'C'},
  {name:'Quest',category:'quantum',field:'Civ',size:2,grade:'D'},
  {name:'Sojourn',category:'quantum',field:'Civ',size:2,grade:'B'},
  {name:'Drifter',category:'quantum',field:'Civ',size:3,grade:'D'},
  {name:'Echo',category:'quantum',field:'Civ',size:3,grade:'D'},
  {name:'Erebos',category:'quantum',field:'Civ',size:3,grade:'A'},
  {name:'Fissure',category:'quantum',field:'Civ',size:3,grade:'C'},
  {name:'Impulse',category:'quantum',field:'Civ',size:3,grade:'B'},
  {name:'Metis',category:'quantum',field:'Civ',size:3,grade:'C'},
  {name:'Ranger',category:'quantum',field:'Civ',size:3,grade:'B'},
  {name:'Tyche',category:'quantum',field:'Civ',size:3,grade:'B'},
  {name:'Wanderer',category:'quantum',field:'Civ',size:3,grade:'C'},
  {name:'Agni',category:'quantum',field:'Ind',size:3,grade:'B'},
  {name:'Bolon',category:'quantum',field:'Ind',size:2,grade:'C'},
  {name:'Colossus',category:'quantum',field:'Ind',size:1,grade:'B'},
  {name:'Goliath',category:'quantum',field:'Ind',size:1,grade:'C'},
  {name:'Huracan',category:'quantum',field:'Ind',size:2,grade:'B'},
  {name:'Kama',category:'quantum',field:'Ind',size:3,grade:'C'},
  {name:'Vesta',category:'quantum',field:'Ind',size:3,grade:'D'},
  {name:'Vulcan',category:'quantum',field:'Ind',size:1,grade:'D'},
  {name:'Yaluk',category:'quantum',field:'Ind',size:2,grade:'D'},
  {name:'Beacon',category:'quantum',field:'Mil',size:1,grade:'C'},
  {name:'Siren',category:'quantum',field:'Mil',size:1,grade:'B'},
  {name:'VK-00',category:'quantum',field:'Mil',size:1,grade:'A'},
  {name:'Crossfield',category:'quantum',field:'Mil',size:2,grade:'C'},
  {name:'XL-1',category:'quantum',field:'Mil',size:2,grade:'A'},
  {name:'Yeager',category:'quantum',field:'Mil',size:2,grade:'B'},
  {name:'Balandin',category:'quantum',field:'Mil',size:3,grade:'B'},
  {name:'Pontes',category:'quantum',field:'Mil',size:3,grade:'C'},
  {name:'TS-2',category:'quantum',field:'Mil',size:3,grade:'A'},
  {name:'Bolt',category:'quantum',field:'Sth',size:2,grade:'B'},
  {name:'Drift',category:'quantum',field:'Sth',size:1,grade:'C'},
  {name:'Nova',category:'quantum',field:'Sth',size:2,grade:'C'},
  {name:'Spectre',category:'quantum',field:'Sth',size:1,grade:'A'},
  {name:'Spicule',category:'quantum',field:'Sth',size:2,grade:'A'},
  {name:'Zephyr',category:'quantum',field:'Sth',size:1,grade:'B'},
  {name:'AllStop',category:'shield',field:'Mil',size:1,grade:'C'},
  {name:'ForceWall',category:'shield',field:'Mil',size:1,grade:'B'},
  {name:'FR-66',category:'shield',field:'Mil',size:1,grade:'A'},
  {name:'SecureHyde',category:'shield',field:'Mil',size:1,grade:'D'},
  {name:'Suldrath',category:'shield',field:'Mil',size:1,grade:'C'},
  {name:'CoverAll',category:'shield',field:'Mil',size:2,grade:'B'},
  {name:'FR-76',category:'shield',field:'Mil',size:2,grade:'A'},
  {name:'FullStop',category:'shield',field:'Mil',size:2,grade:'C'},
  {name:'SecureShield',category:'shield',field:'Mil',size:2,grade:'D'},
  {name:'Sukoran',category:'shield',field:'Mil',size:2,grade:'C'},
  {name:'FR-86',category:'shield',field:'Mil',size:3,grade:'A'},
  {name:'FullBlock',category:'shield',field:'Mil',size:3,grade:'B'},
  {name:'SecureScreen',category:'shield',field:'Mil',size:3,grade:'D'},
  {name:'SureStop',category:'shield',field:'Mil',size:3,grade:'C'},
  {name:'Aspis',category:'shield',field:'Ind',size:2,grade:'C'},
  {name:'Armada',category:'shield',field:'Ind',size:2,grade:'D'},
  {name:'Barbican',category:'shield',field:'Ind',size:3,grade:'B'},
  {name:'Bastion',category:'shield',field:'Ind',size:0,grade:'D'},
  {name:'Bulwark',category:'shield',field:'Ind',size:1,grade:'C'},
  {name:'Castra',category:'shield',field:'Ind',size:0,grade:'C'},
  {name:'Citadel',category:'shield',field:'Ind',size:2,grade:'B'},
  {name:'Guardian',category:'shield',field:'Ind',size:1,grade:'B'},
  {name:'Palisade',category:'shield',field:'Ind',size:1,grade:'A'},
  {name:'Parapet',category:'shield',field:'Ind',size:3,grade:'A'},
  {name:'Rampart',category:'shield',field:'Ind',size:2,grade:'A'},
  {name:'Siege',category:'shield',field:'Ind',size:0,grade:'B'},
  {name:'Steward',category:'shield',field:'Ind',size:1,grade:'D'},
  {name:'Stronghold',category:'shield',field:'Ind',size:3,grade:'C'},
  {name:'Ward',category:'shield',field:'Ind',size:3,grade:'D'},
  {name:'5SA \'Rhada\'',category:'shield',field:'Civ',size:1,grade:'C'},
  {name:'5MA \'Chimalli\'',category:'shield',field:'Civ',size:2,grade:'C'},
  {name:'5CA \'Akura\'',category:'shield',field:'Civ',size:3,grade:'C'},
  {name:'6SA \'Arbiter\'',category:'shield',field:'Civ',size:1,grade:'B'},
  {name:'6MA \'Kozane\'',category:'shield',field:'Civ',size:2,grade:'B'},
  {name:'6CA \'Bila\'',category:'shield',field:'Civ',size:3,grade:'B'},
  {name:'7SA \'Concord\'',category:'shield',field:'Civ',size:1,grade:'A'},
  {name:'7MA \'Lorica\'',category:'shield',field:'Civ',size:2,grade:'A'},
  {name:'7CA \'Nargun\'',category:'shield',field:'Civ',size:3,grade:'A'},
  {name:'ARMOR',category:'shield',field:'Civ',size:3,grade:'B'},
  {name:'BLOC',category:'shield',field:'Civ',size:2,grade:'B'},
  {name:'GUARD',category:'shield',field:'Civ',size:3,grade:'C'},
  {name:'HAVEN',category:'shield',field:'Civ',size:3,grade:'D'},
  {name:'HEX',category:'shield',field:'Civ',size:1,grade:'B'},
  {name:'INK',category:'shield',field:'Civ',size:1,grade:'D'},
  {name:'LOC',category:'shield',field:'Civ',size:0,grade:'B'},
  {name:'PIN',category:'shield',field:'Civ',size:0,grade:'C'},
  {name:'RED',category:'shield',field:'Civ',size:0,grade:'D'},
  {name:'RPEL',category:'shield',field:'Civ',size:2,grade:'D'},
  {name:'STOP',category:'shield',field:'Civ',size:2,grade:'C'},
  {name:'WEB',category:'shield',field:'Civ',size:1,grade:'C'},
  {name:'Bamoty',category:'shield',field:'Cmp',size:2,grade:'D'},
  {name:'Falco',category:'shield',field:'Cmp',size:1,grade:'D'},
  {name:'Haltur',category:'shield',field:'Cmp',size:2,grade:'B'},
  {name:'Jaghte',category:'shield',field:'Cmp',size:1,grade:'B'},
  {name:'Targa',category:'shield',field:'Cmp',size:1,grade:'C'},
  {name:'Trenta',category:'shield',field:'Cmp',size:2,grade:'C'},
  {name:'Cloak',category:'shield',field:'Sth',size:1,grade:'D'},
  {name:'Mirage',category:'shield',field:'Sth',size:1,grade:'A'},
  {name:'Obscura',category:'shield',field:'Sth',size:2,grade:'C'},
  {name:'Sheut',category:'shield',field:'Sth',size:2,grade:'B'},
  {name:'Shimmer',category:'shield',field:'Sth',size:1,grade:'C'},
  {name:'Shroud',category:'shield',field:'Sth',size:2,grade:'D'},
  {name:'Umbra',category:'shield',field:'Sth',size:2,grade:'A'},
  {name:'Veil',category:'shield',field:'Sth',size:1,grade:'B'}
];
